# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_principal.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 756)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/question_block.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    \n"
"    background-image: url(:/icon/icons/background_1.jpg);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    height:30px;\n"
"    border: 1px solid #56799C;\n"
"}\n"
"\n"
"QFrame{\n"
"    border:none;\n"
"}\n"
"\n"
"QToolBar {\n"
"background-color: #273B64 ;\n"
"}\n"
"QToolButton{\n"
"    color:white;\n"
"}\n"
"QToolButton::hover{\n"
"    background-color:#6a91b1;\n"
"    color:#ccc;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.editPesquisar = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.editPesquisar.setFont(font)
        self.editPesquisar.setStyleSheet("")
        self.editPesquisar.setObjectName("editPesquisar")
        self.verticalLayout_4.addWidget(self.editPesquisar)
        self.tableQuestoes = QtWidgets.QTableView(self.frame)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.tableQuestoes.setFont(font)
        self.tableQuestoes.setStyleSheet("QTableView {\n"
"border: 1px solid #56799C;\n"
"}\n"
"\n"
"")
        self.tableQuestoes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableQuestoes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableQuestoes.setObjectName("tableQuestoes")
        self.verticalLayout_4.addWidget(self.tableQuestoes)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:white;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editID = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.editID.setFont(font)
        self.editID.setPlaceholderText("")
        self.editID.setObjectName("editID")
        self.gridLayout_2.addWidget(self.editID, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.editTitulo = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.editTitulo.setFont(font)
        self.editTitulo.setObjectName("editTitulo")
        self.horizontalLayout.addWidget(self.editTitulo)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.editPergunta = QtWidgets.QTextEdit(self.frame_2)
        self.editPergunta.setMinimumSize(QtCore.QSize(0, 140))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editPergunta.setFont(font)
        self.editPergunta.setStyleSheet("    border: 1px solid #56799C;")
        self.editPergunta.setObjectName("editPergunta")
        self.gridLayout_2.addWidget(self.editPergunta, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonImage = QtWidgets.QPushButton(self.frame_2)
        self.buttonImage.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/tag-jpg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonImage.setIcon(icon1)
        self.buttonImage.setIconSize(QtCore.QSize(20, 20))
        self.buttonImage.setFlat(True)
        self.buttonImage.setObjectName("buttonImage")
        self.horizontalLayout_3.addWidget(self.buttonImage)
        self.buttonBold = QtWidgets.QPushButton(self.frame_2)
        self.buttonBold.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBold.setIcon(icon2)
        self.buttonBold.setIconSize(QtCore.QSize(20, 20))
        self.buttonBold.setFlat(True)
        self.buttonBold.setObjectName("buttonBold")
        self.horizontalLayout_3.addWidget(self.buttonBold)
        self.buttonItalic = QtWidgets.QPushButton(self.frame_2)
        self.buttonItalic.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonItalic.setIcon(icon3)
        self.buttonItalic.setIconSize(QtCore.QSize(20, 20))
        self.buttonItalic.setFlat(True)
        self.buttonItalic.setObjectName("buttonItalic")
        self.horizontalLayout_3.addWidget(self.buttonItalic)
        self.buttonUnderline = QtWidgets.QPushButton(self.frame_2)
        self.buttonUnderline.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUnderline.setIcon(icon4)
        self.buttonUnderline.setIconSize(QtCore.QSize(20, 20))
        self.buttonUnderline.setFlat(True)
        self.buttonUnderline.setObjectName("buttonUnderline")
        self.horizontalLayout_3.addWidget(self.buttonUnderline)
        self.buttonListBulleted = QtWidgets.QPushButton(self.frame_2)
        self.buttonListBulleted.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/unordered-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonListBulleted.setIcon(icon5)
        self.buttonListBulleted.setIconSize(QtCore.QSize(20, 20))
        self.buttonListBulleted.setFlat(True)
        self.buttonListBulleted.setObjectName("buttonListBulleted")
        self.horizontalLayout_3.addWidget(self.buttonListBulleted)
        self.buttonListNumbered = QtWidgets.QPushButton(self.frame_2)
        self.buttonListNumbered.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/order-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonListNumbered.setIcon(icon6)
        self.buttonListNumbered.setIconSize(QtCore.QSize(20, 20))
        self.buttonListNumbered.setFlat(True)
        self.buttonListNumbered.setObjectName("buttonListNumbered")
        self.horizontalLayout_3.addWidget(self.buttonListNumbered)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.splitter)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:white;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.editCategoria = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.editCategoria.setFont(font)
        self.editCategoria.setStyleSheet("")
        self.editCategoria.setText("")
        self.editCategoria.setObjectName("editCategoria")
        self.horizontalLayout_5.addWidget(self.editCategoria)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonImageR = QtWidgets.QPushButton(self.frame_3)
        self.buttonImageR.setText("")
        self.buttonImageR.setIcon(icon1)
        self.buttonImageR.setIconSize(QtCore.QSize(20, 20))
        self.buttonImageR.setFlat(True)
        self.buttonImageR.setObjectName("buttonImageR")
        self.horizontalLayout_4.addWidget(self.buttonImageR)
        self.buttonBoldR = QtWidgets.QPushButton(self.frame_3)
        self.buttonBoldR.setText("")
        self.buttonBoldR.setIcon(icon2)
        self.buttonBoldR.setIconSize(QtCore.QSize(20, 20))
        self.buttonBoldR.setFlat(True)
        self.buttonBoldR.setObjectName("buttonBoldR")
        self.horizontalLayout_4.addWidget(self.buttonBoldR)
        self.buttonItalicR = QtWidgets.QPushButton(self.frame_3)
        self.buttonItalicR.setText("")
        self.buttonItalicR.setIcon(icon3)
        self.buttonItalicR.setIconSize(QtCore.QSize(20, 20))
        self.buttonItalicR.setFlat(True)
        self.buttonItalicR.setObjectName("buttonItalicR")
        self.horizontalLayout_4.addWidget(self.buttonItalicR)
        self.buttonUnderlineR = QtWidgets.QPushButton(self.frame_3)
        self.buttonUnderlineR.setText("")
        self.buttonUnderlineR.setIcon(icon4)
        self.buttonUnderlineR.setIconSize(QtCore.QSize(20, 20))
        self.buttonUnderlineR.setFlat(True)
        self.buttonUnderlineR.setObjectName("buttonUnderlineR")
        self.horizontalLayout_4.addWidget(self.buttonUnderlineR)
        self.buttonListBulletedR = QtWidgets.QPushButton(self.frame_3)
        self.buttonListBulletedR.setText("")
        self.buttonListBulletedR.setIcon(icon5)
        self.buttonListBulletedR.setIconSize(QtCore.QSize(20, 20))
        self.buttonListBulletedR.setFlat(True)
        self.buttonListBulletedR.setObjectName("buttonListBulletedR")
        self.horizontalLayout_4.addWidget(self.buttonListBulletedR)
        self.buttonListNumberedR = QtWidgets.QPushButton(self.frame_3)
        self.buttonListNumberedR.setText("")
        self.buttonListNumberedR.setIcon(icon6)
        self.buttonListNumberedR.setIconSize(QtCore.QSize(20, 20))
        self.buttonListNumberedR.setFlat(True)
        self.buttonListNumberedR.setObjectName("buttonListNumberedR")
        self.horizontalLayout_4.addWidget(self.buttonListNumberedR)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.editResposta = QtWidgets.QTextEdit(self.frame_3)
        self.editResposta.setMinimumSize(QtCore.QSize(0, 140))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editResposta.setFont(font)
        self.editResposta.setStyleSheet("border: 1px solid #56799C;")
        self.editResposta.setObjectName("editResposta")
        self.verticalLayout_2.addWidget(self.editResposta)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCancelar.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCancelar.setFont(font)
        self.buttonCancelar.setStyleSheet("QPushButton{\n"
"    background-color:#d9534f;\n"
"    color:white;\n"
"    border:none;\n"
"    width:150px;\n"
"}")
        self.buttonCancelar.setIconSize(QtCore.QSize(48, 48))
        self.buttonCancelar.setFlat(False)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout_2.addWidget(self.buttonCancelar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUpdate.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonUpdate.setFont(font)
        self.buttonUpdate.setStyleSheet("QPushButton{\n"
"    background-color:#337ab7;\n"
"    color:white;\n"
"    border:none;\n"
"    width:150px;\n"
"}")
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.horizontalLayout_2.addWidget(self.buttonUpdate)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSalvar.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSalvar.setFont(font)
        self.buttonSalvar.setStyleSheet("QPushButton{\n"
"    background-color:#5cb85c;\n"
"    color:white;\n"
"    border:none;\n"
"    width:150px;\n"
"}")
        self.buttonSalvar.setIconSize(QtCore.QSize(48, 48))
        self.buttonSalvar.setAutoDefault(False)
        self.buttonSalvar.setDefault(False)
        self.buttonSalvar.setFlat(False)
        self.buttonSalvar.setObjectName("buttonSalvar")
        self.horizontalLayout_2.addWidget(self.buttonSalvar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNovaQuestao = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovaQuestao.setIcon(icon7)
        self.actionNovaQuestao.setObjectName("actionNovaQuestao")
        self.actionCategoria = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/images/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCategoria.setIcon(icon8)
        self.actionCategoria.setObjectName("actionCategoria")
        self.actionDeletar_Questao = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeletar_Questao.setIcon(icon9)
        self.actionDeletar_Questao.setObjectName("actionDeletar_Questao")
        self.actionBackup = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icons/backup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackup.setIcon(icon10)
        self.actionBackup.setObjectName("actionBackup")
        self.actionDoacoes = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icons/donate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDoacoes.setIcon(icon11)
        self.actionDoacoes.setObjectName("actionDoacoes")
        self.actionRestaurar = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icons/restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestaurar.setIcon(icon12)
        self.actionRestaurar.setObjectName("actionRestaurar")
        self.toolBar.addAction(self.actionNovaQuestao)
        self.toolBar.addAction(self.actionDeletar_Questao)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBackup)
        self.toolBar.addAction(self.actionRestaurar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDoacoes)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.editPesquisar, self.tableQuestoes)
        MainWindow.setTabOrder(self.tableQuestoes, self.editTitulo)
        MainWindow.setTabOrder(self.editTitulo, self.editPergunta)
        MainWindow.setTabOrder(self.editPergunta, self.editCategoria)
        MainWindow.setTabOrder(self.editCategoria, self.editResposta)
        MainWindow.setTabOrder(self.editResposta, self.buttonCancelar)
        MainWindow.setTabOrder(self.buttonCancelar, self.buttonSalvar)
        MainWindow.setTabOrder(self.buttonSalvar, self.buttonListBulleted)
        MainWindow.setTabOrder(self.buttonListBulleted, self.buttonListNumbered)
        MainWindow.setTabOrder(self.buttonListNumbered, self.editID)
        MainWindow.setTabOrder(self.editID, self.buttonBold)
        MainWindow.setTabOrder(self.buttonBold, self.buttonItalic)
        MainWindow.setTabOrder(self.buttonItalic, self.buttonUnderline)
        MainWindow.setTabOrder(self.buttonUnderline, self.buttonImageR)
        MainWindow.setTabOrder(self.buttonImageR, self.buttonBoldR)
        MainWindow.setTabOrder(self.buttonBoldR, self.buttonItalicR)
        MainWindow.setTabOrder(self.buttonItalicR, self.buttonUnderlineR)
        MainWindow.setTabOrder(self.buttonUnderlineR, self.buttonListBulletedR)
        MainWindow.setTabOrder(self.buttonListBulletedR, self.buttonListNumberedR)
        MainWindow.setTabOrder(self.buttonListNumberedR, self.buttonImage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Banco de Questões"))
        self.label.setText(_translate("MainWindow", "Pesquisar por questões"))
        self.editPesquisar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Digite um termo para buscar</p></body></html>"))
        self.editPesquisar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Digite um termo para buscar</p></body></html>"))
        self.editPesquisar.setPlaceholderText(_translate("MainWindow", "Pesquisar..."))
        self.label_5.setText(_translate("MainWindow", "Título:"))
        self.editTitulo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Título da Questão</p></body></html>"))
        self.editTitulo.setPlaceholderText(_translate("MainWindow", "Título da questão"))
        self.editPergunta.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enunciado da questão</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Questão"))
        self.label_2.setText(_translate("MainWindow", "Resposta"))
        self.label_4.setText(_translate("MainWindow", "Palavras Chave"))
        self.editCategoria.setToolTip(_translate("MainWindow", "<html><head/><body><p>Palavras chave separadas por &quot;;&quot;</p></body></html>"))
        self.editCategoria.setPlaceholderText(_translate("MainWindow", "Palavra Chave 1; Palavra chave2;..."))
        self.editResposta.setToolTip(_translate("MainWindow", "<html><head/><body><p>Resposta da questão</p></body></html>"))
        self.buttonCancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cancelar</p></body></html>"))
        self.buttonCancelar.setText(_translate("MainWindow", "&Cancelar"))
        self.buttonUpdate.setText(_translate("MainWindow", "&Atualizar"))
        self.buttonSalvar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Salvar</p></body></html>"))
        self.buttonSalvar.setText(_translate("MainWindow", "&Salvar"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNovaQuestao.setText(_translate("MainWindow", "Nova Questão"))
        self.actionNovaQuestao.setToolTip(_translate("MainWindow", "<html><head/><body><p>Nova Questão</p></body></html>"))
        self.actionCategoria.setText(_translate("MainWindow", "Categoria"))
        self.actionDeletar_Questao.setText(_translate("MainWindow", "Deletar Questão"))
        self.actionDeletar_Questao.setToolTip(_translate("MainWindow", "Deletar Questão"))
        self.actionBackup.setText(_translate("MainWindow", "Backup"))
        self.actionBackup.setToolTip(_translate("MainWindow", "Backup"))
        self.actionDoacoes.setText(_translate("MainWindow", "Donate"))
        self.actionDoacoes.setToolTip(_translate("MainWindow", "Donate"))
        self.actionRestaurar.setText(_translate("MainWindow", "Restaurar"))
import view.icon_rc
